
package com.totvs.technology.ecm.dm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardIndexService", targetNamespace = "http://ws.dm.ecm.technology.totvs.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.totvs.technology.ecm.dm.ws.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface CardIndexService {


    /**
     * 
     * @param publisherId
     * @param username
     * @param parentDocumentId
     * @param customEvents
     * @param documentDescription
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createSimpleCardIndex")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createSimpleCardIndex(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "parentDocumentId", partName = "parentDocumentId")
        int parentDocumentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.FormDatasetDTOArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getFormDatasets")
    @WebResult(name = "result", partName = "result")
    public FormDatasetDTOArray getFormDatasets(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param colleagueId
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getActiveCardIndex")
    @WebResult(name = "cardIndex", partName = "cardIndex")
    public DocumentDtoArray getActiveCardIndex(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param publisherId
     * @param username
     * @param datasetName
     * @param descriptionField
     * @param customEvents
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateSimpleCardIndexWithDataset")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateSimpleCardIndexWithDataset(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "descriptionField", partName = "descriptionField")
        String descriptionField,
        @WebParam(name = "datasetName", partName = "datasetName")
        String datasetName,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents)
        throws Exception_Exception
    ;

    /**
     * 
     * @param persistenceType
     * @param publisherId
     * @param username
     * @param parentDocumentId
     * @param datasetName
     * @param relatedDatasets
     * @param customEvents
     * @param documentDescription
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createSimpleCardIndexWithRelatedDatasets")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createSimpleCardIndexWithRelatedDatasets(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "parentDocumentId", partName = "parentDocumentId")
        int parentDocumentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "datasetName", partName = "datasetName")
        String datasetName,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents,
        @WebParam(name = "persistenceType", partName = "persistenceType")
        int persistenceType,
        @WebParam(name = "relatedDatasets", partName = "relatedDatasets")
        StringArray relatedDatasets)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.CardEventDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getCustomizationEvents")
    @WebResult(name = "result", partName = "result")
    public CardEventDtoArray getCustomizationEvents(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param publisherId
     * @param username
     * @param parentDocumentId
     * @param datasetName
     * @param customEvents
     * @param documentDescription
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createSimpleCardIndexWithDataset")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createSimpleCardIndexWithDataset(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "parentDocumentId", partName = "parentDocumentId")
        int parentDocumentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "datasetName", partName = "datasetName")
        String datasetName,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents)
        throws Exception_Exception
    ;

    /**
     * 
     * @param publisherId
     * @param username
     * @param generalInfo
     * @param datasetName
     * @param descriptionField
     * @param relatedDatasets
     * @param customEvents
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateSimpleCardIndexWithRelatedDatasets")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateSimpleCardIndexWithRelatedDatasets(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "descriptionField", partName = "descriptionField")
        String descriptionField,
        @WebParam(name = "datasetName", partName = "datasetName")
        String datasetName,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents,
        @WebParam(name = "generalInfo", partName = "generalInfo")
        GeneralInfoDto generalInfo,
        @WebParam(name = "relatedDatasets", partName = "relatedDatasets")
        StringArray relatedDatasets)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getAttachmentsList")
    @WebResult(name = "result", partName = "result")
    public StringArray getAttachmentsList(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param colleagueId
     * @param nomeArquivo
     * @param companyId
     * @param password
     * @param documentId
     * @param version
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod(action = "getCardIndexContent")
    @WebResult(name = "folder", partName = "folder")
    public byte[] getCardIndexContent(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId,
        @WebParam(name = "version", partName = "version")
        int version,
        @WebParam(name = "nomeArquivo", partName = "nomeArquivo")
        String nomeArquivo)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param colleagueId
     * @param companyId
     * @param password
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getCardIndexesWithoutApprover")
    @WebResult(name = "result", partName = "result")
    public DocumentDtoArray getCardIndexesWithoutApprover(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param publisherId
     * @param username
     * @param generalInfo
     * @param datasetName
     * @param descriptionField
     * @param customEvents
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateSimpleCardIndexWithDatasetAndGeneralInfo")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateSimpleCardIndexWithDatasetAndGeneralInfo(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "descriptionField", partName = "descriptionField")
        String descriptionField,
        @WebParam(name = "datasetName", partName = "datasetName")
        String datasetName,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents,
        @WebParam(name = "generalInfo", partName = "generalInfo")
        GeneralInfoDto generalInfo)
        throws Exception_Exception
    ;

    /**
     * 
     * @param username
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getFormFields")
    @WebResult(name = "result", partName = "result")
    public StringArray getFormFields(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param persistenceType
     * @param publisherId
     * @param username
     * @param parentDocumentId
     * @param datasetName
     * @param customEvents
     * @param documentDescription
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createSimpleCardIndexWithDatasetPersisteType")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createSimpleCardIndexWithDatasetPersisteType(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "parentDocumentId", partName = "parentDocumentId")
        int parentDocumentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "datasetName", partName = "datasetName")
        String datasetName,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents,
        @WebParam(name = "persistenceType", partName = "persistenceType")
        int persistenceType)
        throws Exception_Exception
    ;

    /**
     * 
     * @param publisherId
     * @param username
     * @param descriptionField
     * @param customEvents
     * @param attachments
     * @param cardDescription
     * @param companyId
     * @param password
     * @param documentId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateSimpleCardIndex")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateSimpleCardIndex(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "cardDescription", partName = "cardDescription")
        String cardDescription,
        @WebParam(name = "descriptionField", partName = "descriptionField")
        String descriptionField,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "customEvents", partName = "customEvents")
        CardEventDtoArray customEvents)
        throws Exception_Exception
    ;

}
