
package com.totvs.technology.ecm.dm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import net.java.dev.jaxb.array.IntArray;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentService", targetNamespace = "http://ws.dm.ecm.technology.totvs.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    com.totvs.technology.ecm.dm.ws.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface DocumentService {


    /**
     * 
     * @param password
     * @param companyId
     * @param nrResultados
     * @param colleagueId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "findMostPopularDocuments")
    @WebResult(name = "result", partName = "result")
    public DocumentDtoArray findMostPopularDocuments(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId,
        @WebParam(name = "nrResultados", partName = "nrResultados")
        int nrResultados)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param externalDocumentnId
     * @param colleagueId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDocumentByExternalId")
    @WebResult(name = "Documents", partName = "Documents")
    public DocumentDtoArray getDocumentByExternalId(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "externalDocumentnId", partName = "externalDocumentnId")
        String externalDocumentnId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param security
     * @param attachments
     * @param document
     * @param relatedDocuments
     * @param approversWithLevels
     * @param levels
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createDocumentWithApprovementLevels")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createDocumentWithApprovementLevels(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "Document", partName = "Document")
        DocumentDtoArray document,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "security", partName = "security")
        DocumentSecurityConfigDtoArray security,
        @WebParam(name = "ApproversWithLevels", partName = "ApproversWithLevels")
        ApproverWithLevelDtoArray approversWithLevels,
        @WebParam(name = "Levels", partName = "Levels")
        ApprovalLevelDtoArray levels,
        @WebParam(name = "RelatedDocuments", partName = "RelatedDocuments")
        RelatedDocumentDtoArray relatedDocuments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param publisherId
     * @param documentId
     * @param userId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "destroyDocumentApproval")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray destroyDocumentApproval(
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param password
     * @param limit
     * @param lastRowId
     * @param user
     * @param colleagueId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "findMostPopularDocumentsOnDemand")
    @WebResult(name = "result", partName = "result")
    public DocumentDtoArray findMostPopularDocumentsOnDemand(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId,
        @WebParam(name = "limit", partName = "limit")
        int limit,
        @WebParam(name = "lastRowId", partName = "lastRowId")
        int lastRowId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentApprovalStatusDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDocumentApprovalStatus")
    @WebResult(name = "DocumentApprovalStatusDtos", partName = "DocumentApprovalStatusDtos")
    public DocumentApprovalStatusDtoArray getDocumentApprovalStatus(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param username
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "validateIntegrationRequirements")
    @WebResult(name = "result", partName = "result")
    public String validateIntegrationRequirements(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param colleagueId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDocumentVersion")
    @WebResult(name = "folder", partName = "folder")
    public DocumentDtoArray getDocumentVersion(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param destFolderId
     * @param colleagueId
     * @param username
     * @param documentIds
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(action = "moveDocument")
    @WebResult(name = "result", partName = "result")
    public String moveDocument(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentIds", partName = "documentIds")
        IntArray documentIds,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId,
        @WebParam(name = "destFolderId", partName = "destFolderId")
        int destFolderId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param msg
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @param status
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateDocumentConversionStatus")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateDocumentConversionStatus(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version,
        @WebParam(name = "status", partName = "status")
        int status,
        @WebParam(name = "msg", partName = "msg")
        String msg)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod(action = "getUserPermissions")
    @WebResult(name = "result", partName = "result")
    public int getUserPermissions(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param user
     * @param colleagueId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "deleteDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray deleteDocument(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param publisherId
     * @param documentDescription
     * @param attachments
     * @param documentId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateSimpleDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateSimpleDocument(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentSecurityConfigDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getSecurity")
    @WebResult(name = "Security", partName = "Security")
    public DocumentSecurityConfigDtoArray getSecurity(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentDescription
     * @param attachments
     * @param parentDocumentId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createSimpleDocumentPrivate")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createSimpleDocumentPrivate(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "parentDocumentId", partName = "parentDocumentId")
        int parentDocumentId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param companyId
     * @param password
     * @param approved
     * @param approverId
     * @param observation
     * @param documentId
     * @param userId
     * @param version
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "approveDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray approveDocument(
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "userId", partName = "userId")
        String userId,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version,
        @WebParam(name = "approverId", partName = "approverId")
        String approverId,
        @WebParam(name = "approved", partName = "approved")
        boolean approved,
        @WebParam(name = "observation", partName = "observation")
        String observation)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param publisherId
     * @param documentDescription
     * @param attachments
     * @param parentDocumentId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createSimpleDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createSimpleDocument(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "parentDocumentId", partName = "parentDocumentId")
        int parentDocumentId,
        @WebParam(name = "publisherId", partName = "publisherId")
        String publisherId,
        @WebParam(name = "documentDescription", partName = "documentDescription")
        String documentDescription,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param colleagueId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getActiveDocument")
    @WebResult(name = "folder", partName = "folder")
    public DocumentDtoArray getActiveDocument(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param user
     * @param colleagueId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "destroyDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray destroyDocument(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.ApproverWithLevelDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getApprovers")
    @WebResult(name = "Approvers", partName = "Approvers")
    public ApproverWithLevelDtoArray getApprovers(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param user
     * @param colleagueId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "restoreDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray restoreDocument(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param security
     * @param attachments
     * @param document
     * @param relatedDocuments
     * @param approvers
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "createDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray createDocument(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "Document", partName = "Document")
        DocumentDtoArray document,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "security", partName = "security")
        DocumentSecurityConfigDtoArray security,
        @WebParam(name = "Approvers", partName = "Approvers")
        ApproverDtoArray approvers,
        @WebParam(name = "RelatedDocuments", partName = "RelatedDocuments")
        RelatedDocumentDtoArray relatedDocuments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @throws Exception_Exception
     */
    @WebMethod(action = "removeSecurity")
    public void removeSecurity(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param permissionType
     * @param password
     * @param companyId
     * @param restrictionType
     * @param documentId
     * @param version
     * @param colleagueId
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateGroupSecurityType")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateGroupSecurityType(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version,
        @WebParam(name = "permissionType", partName = "permissionType")
        int permissionType,
        @WebParam(name = "restrictionType", partName = "restrictionType")
        int restrictionType,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param user
     * @param colleagueId
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "findRecycledDocuments")
    @WebResult(name = "result", partName = "result")
    public DocumentDtoArray findRecycledDocuments(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.RelatedDocumentDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getRelatedDocuments")
    @WebResult(name = "RelatedDocuments", partName = "RelatedDocuments")
    public RelatedDocumentDtoArray getRelatedDocuments(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param security
     * @param attachments
     * @param document
     * @param relatedDocuments
     * @param approversWithLevels
     * @param levels
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateDocumentWithApprovementLevels")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateDocumentWithApprovementLevels(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "Document", partName = "Document")
        DocumentDtoArray document,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "security", partName = "security")
        DocumentSecurityConfigDtoArray security,
        @WebParam(name = "ApproversWithLevels", partName = "ApproversWithLevels")
        ApproverWithLevelDtoArray approversWithLevels,
        @WebParam(name = "Levels", partName = "Levels")
        ApprovalLevelDtoArray levels,
        @WebParam(name = "RelatedDocuments", partName = "RelatedDocuments")
        RelatedDocumentDtoArray relatedDocuments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param user
     * @param version
     * @param colleagueId
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "copyDocumentToUploadArea")
    @WebResult(name = "result", partName = "result")
    public StringArray copyDocumentToUploadArea(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param username
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod(action = "getReportSubject")
    @WebResult(name = "topicId", partName = "topicId")
    public int getReportSubjectId(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param security
     * @param attachments
     * @param document
     * @param relatedDocuments
     * @param approvers
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.WebServiceMessageArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "updateDocument")
    @WebResult(name = "result", partName = "result")
    public WebServiceMessageArray updateDocument(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "Document", partName = "Document")
        DocumentDtoArray document,
        @WebParam(name = "Attachments", partName = "Attachments")
        AttachmentArray attachments,
        @WebParam(name = "security", partName = "security")
        DocumentSecurityConfigDtoArray security,
        @WebParam(name = "Approvers", partName = "Approvers")
        ApproverDtoArray approvers,
        @WebParam(name = "RelatedDocuments", partName = "RelatedDocuments")
        RelatedDocumentDtoArray relatedDocuments)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param documentId
     * @param version
     * @param username
     * @return
     *     returns com.totvs.technology.ecm.dm.ws.DocumentApprovementHistoryDtoArray
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDocumentApprovalHistory")
    @WebResult(name = "DocumentApprovementHistoryDtos", partName = "DocumentApprovementHistoryDtos")
    public DocumentApprovementHistoryDtoArray getDocumentApprovalHistory(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "version", partName = "version")
        int version)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param companyId
     * @param nomeArquivo
     * @param documentId
     * @param documentoVersao
     * @param colleagueId
     * @param username
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod(action = "getDocumentContent")
    @WebResult(name = "folder", partName = "folder")
    public byte[] getDocumentContent(
        @WebParam(name = "username", partName = "username")
        String username,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "companyId", partName = "companyId")
        int companyId,
        @WebParam(name = "documentId", partName = "documentId")
        int documentId,
        @WebParam(name = "colleagueId", partName = "colleagueId")
        String colleagueId,
        @WebParam(name = "documentoVersao", partName = "documentoVersao")
        int documentoVersao,
        @WebParam(name = "nomeArquivo", partName = "nomeArquivo")
        String nomeArquivo)
        throws Exception_Exception
    ;

}
