
package com.totvs.technology.ecm.dm.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ECMCardIndexServiceService", targetNamespace = "http://ws.dm.ecm.technology.totvs.com/", wsdlLocation = "http://bancovotorantim.fluig.com/webdesk/ECMCardIndexService?wsdl")
public class ECMCardIndexServiceService
    extends Service
{

    private final static URL ECMCARDINDEXSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ECMCARDINDEXSERVICESERVICE_EXCEPTION;
    private final static QName ECMCARDINDEXSERVICESERVICE_QNAME = new QName("http://ws.dm.ecm.technology.totvs.com/", "ECMCardIndexServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bancovotorantim.fluig.com/webdesk/ECMCardIndexService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECMCARDINDEXSERVICESERVICE_WSDL_LOCATION = url;
        ECMCARDINDEXSERVICESERVICE_EXCEPTION = e;
    }

    public ECMCardIndexServiceService() {
        super(__getWsdlLocation(), ECMCARDINDEXSERVICESERVICE_QNAME);
    }

    public ECMCardIndexServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECMCARDINDEXSERVICESERVICE_QNAME, features);
    }

    public ECMCardIndexServiceService(URL wsdlLocation) {
        super(wsdlLocation, ECMCARDINDEXSERVICESERVICE_QNAME);
    }

    public ECMCardIndexServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECMCARDINDEXSERVICESERVICE_QNAME, features);
    }

    public ECMCardIndexServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ECMCardIndexServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardIndexService
     */
    @WebEndpoint(name = "CardIndexServicePort")
    public CardIndexService getCardIndexServicePort() {
        return super.getPort(new QName("http://ws.dm.ecm.technology.totvs.com/", "CardIndexServicePort"), CardIndexService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardIndexService
     */
    @WebEndpoint(name = "CardIndexServicePort")
    public CardIndexService getCardIndexServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dm.ecm.technology.totvs.com/", "CardIndexServicePort"), CardIndexService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECMCARDINDEXSERVICESERVICE_EXCEPTION!= null) {
            throw ECMCARDINDEXSERVICESERVICE_EXCEPTION;
        }
        return ECMCARDINDEXSERVICESERVICE_WSDL_LOCATION;
    }

}
