
package com.totvs.technology.ecm.dm.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ECMDocumentServiceService", targetNamespace = "http://ws.dm.ecm.technology.totvs.com/", wsdlLocation = "https://brfluigqa.dimensiondata.com/webdesk/ECMDocumentService?wsdl")
public class ECMDocumentServiceService
    extends Service
{

    private final static URL ECMDOCUMENTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ECMDOCUMENTSERVICESERVICE_EXCEPTION;
    private final static QName ECMDOCUMENTSERVICESERVICE_QNAME = new QName("http://ws.dm.ecm.technology.totvs.com/", "ECMDocumentServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://brfluigqa.dimensiondata.com/webdesk/ECMDocumentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECMDOCUMENTSERVICESERVICE_WSDL_LOCATION = url;
        ECMDOCUMENTSERVICESERVICE_EXCEPTION = e;
    }

    public ECMDocumentServiceService() {
        super(__getWsdlLocation(), ECMDOCUMENTSERVICESERVICE_QNAME);
    }

    public ECMDocumentServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECMDOCUMENTSERVICESERVICE_QNAME, features);
    }

    public ECMDocumentServiceService(URL wsdlLocation) {
        super(wsdlLocation, ECMDOCUMENTSERVICESERVICE_QNAME);
    }

    public ECMDocumentServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECMDOCUMENTSERVICESERVICE_QNAME, features);
    }

    public ECMDocumentServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ECMDocumentServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentService
     */
    @WebEndpoint(name = "DocumentServicePort")
    public DocumentService getDocumentServicePort() {
        return super.getPort(new QName("http://ws.dm.ecm.technology.totvs.com/", "DocumentServicePort"), DocumentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentService
     */
    @WebEndpoint(name = "DocumentServicePort")
    public DocumentService getDocumentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dm.ecm.technology.totvs.com/", "DocumentServicePort"), DocumentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECMDOCUMENTSERVICESERVICE_EXCEPTION!= null) {
            throw ECMDOCUMENTSERVICESERVICE_EXCEPTION;
        }
        return ECMDOCUMENTSERVICESERVICE_WSDL_LOCATION;
    }

}
